"""add image_url to broadcast_configs

Revision ID: 4d37a208ec86
Revises: e1be019b6a14
Create Date: 2026-03-01 21:03:18.651227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d37a208ec86'
down_revision = 'e1be019b6a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broadcast_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broadcast_configs', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
