"""Add_WithdrawRequest

Revision ID: 6128782a2212
Revises: 96891f0fa0bc
Create Date: 2026-02-28 00:58:56.454279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6128782a2212'
down_revision = '96891f0fa0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdraw_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_account', sa.String(length=100), nullable=True),
    sa.Column('payment_image', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('audit_remark', sa.String(length=255), nullable=True),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('audit_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withdraw_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdraw_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdraw_requests_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdraw_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdraw_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_withdraw_requests_status'))

    op.drop_table('withdraw_requests')
    # ### end Alembic commands ###
