"""Add Order and Finance models

Revision ID: 96891f0fa0bc
Revises: fdc2d0bb174b
Create Date: 2026-02-28 00:16:17.804600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96891f0fa0bc'
down_revision = 'fdc2d0bb174b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balance_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_logs_user_id'), ['user_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('god_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('project_item', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('player_income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('platform_income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_frozen', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['god_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_god_id'), ['god_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_no'), ['order_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    op.create_table('commission_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_logs_user_id'))

    op.drop_table('commission_logs')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_staff_id'))
        batch_op.drop_index(batch_op.f('ix_orders_player_id'))
        batch_op.drop_index(batch_op.f('ix_orders_order_no'))
        batch_op.drop_index(batch_op.f('ix_orders_god_id'))

    op.drop_table('orders')
    with op.batch_alter_table('balance_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_logs_user_id'))

    op.drop_table('balance_logs')
    # ### end Alembic commands ###
