"""rebuild orders with project system

Revision ID: ae85512f7f17
Revises: 6128782a2212
Create Date: 2026-02-28 10:25:48.313559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae85512f7f17'
down_revision = '6128782a2212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('player_nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('badge', sa.String(length=50), nullable=True),
    sa.Column('user_code', sa.String(length=20), nullable=True),
    sa.Column('kook_id', sa.String(length=50), nullable=True),
    sa.Column('kook_username', sa.String(length=100), nullable=True),
    sa.Column('kook_bound', sa.Boolean(), nullable=True),
    sa.Column('wechat_openid', sa.String(length=100), nullable=True),
    sa.Column('wechat_bound', sa.Boolean(), nullable=True),
    sa.Column('m_coin', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('m_coin_gift', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('m_bean', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('m_bean_frozen', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('vip_level', sa.String(length=50), nullable=True),
    sa.Column('vip_discount', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('anonymous_recharge', sa.Boolean(), nullable=True),
    sa.Column('anonymous_gift_send', sa.Boolean(), nullable=True),
    sa.Column('anonymous_gift_recv', sa.Boolean(), nullable=True),
    sa.Column('anonymous_upgrade', sa.Boolean(), nullable=True),
    sa.Column('broadcast_channel', sa.String(length=100), nullable=True),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('register_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_code')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_kook_id'), ['kook_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_nickname'), ['nickname'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_player_nickname'), ['player_nickname'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('balance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balance_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_logs_user_id'), ['user_id'], unique=False)

    op.create_table('project_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_casual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_tech', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_god', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_pro', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('billing_type', sa.String(length=20), nullable=True),
    sa.Column('project_type', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_items_project_id'), ['project_id'], unique=False)

    op.create_table('withdraw_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_account', sa.String(length=100), nullable=True),
    sa.Column('payment_image', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('audit_remark', sa.String(length=255), nullable=True),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('audit_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withdraw_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdraw_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdraw_requests_user_id'), ['user_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('project_item_id', sa.Integer(), nullable=True),
    sa.Column('price_tier', sa.String(length=20), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('extra_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('addon_desc', sa.String(length=200), nullable=True),
    sa.Column('addon_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('boss_discount', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('player_earning', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shop_earning', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('duration', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('freeze_status', sa.String(length=20), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('fill_time', sa.DateTime(), nullable=True),
    sa.Column('report_time', sa.DateTime(), nullable=True),
    sa.Column('confirm_time', sa.DateTime(), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.Column('refund_time', sa.DateTime(), nullable=True),
    sa.Column('auto_confirm_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boss_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_item_id'], ['project_items.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_boss_id'), ['boss_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_no'), ['order_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_project_item_id'), ['project_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    op.create_table('commission_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_logs_user_id'))

    op.drop_table('commission_logs')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_staff_id'))
        batch_op.drop_index(batch_op.f('ix_orders_project_item_id'))
        batch_op.drop_index(batch_op.f('ix_orders_player_id'))
        batch_op.drop_index(batch_op.f('ix_orders_order_no'))
        batch_op.drop_index(batch_op.f('ix_orders_boss_id'))

    op.drop_table('orders')
    with op.batch_alter_table('withdraw_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdraw_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_withdraw_requests_status'))

    op.drop_table('withdraw_requests')
    with op.batch_alter_table('project_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_items_project_id'))

    op.drop_table('project_items')
    with op.batch_alter_table('balance_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_logs_user_id'))

    op.drop_table('balance_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_player_nickname'))
        batch_op.drop_index(batch_op.f('ix_users_nickname'))
        batch_op.drop_index(batch_op.f('ix_users_kook_id'))

    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
