"""empty message

Revision ID: e1be019b6a14
Revises: b3ffdcbe856c
Create Date: 2026-03-01 02:31:17.878073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1be019b6a14'
down_revision = 'b3ffdcbe856c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_type', sa.String(length=30), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('template', sa.Text(), nullable=True),
    sa.Column('channel_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('broadcast_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broadcast_configs_broadcast_type'), ['broadcast_type'], unique=False)

    op.create_table('gifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('gift_type', sa.String(length=20), nullable=True),
    sa.Column('broadcast_template', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vip_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('min_experience', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gift_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('gift_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('player_earning', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shop_earning', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('freeze_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('refund_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boss_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gift_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gift_orders_boss_id'), ['boss_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gift_orders_gift_id'), ['gift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gift_orders_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gift_orders_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gift_orders_status'), ['status'], unique=False)

    op.create_table('intimacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boss_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('boss_id', 'player_id', name='uq_boss_player_intimacy')
    )
    with op.batch_alter_table('intimacies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intimacies_boss_id'), ['boss_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intimacies_player_id'), ['player_id'], unique=False)

    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_operator_id'), ['operator_id'], unique=False)

    op.create_table('upgrade_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_level', sa.String(length=50), nullable=True),
    sa.Column('to_level', sa.String(length=50), nullable=True),
    sa.Column('benefit_status', sa.String(length=20), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upgrade_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upgrade_records_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upgrade_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upgrade_records_user_id'))

    op.drop_table('upgrade_records')
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_logs_operator_id'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_action_type'))

    op.drop_table('operation_logs')
    with op.batch_alter_table('intimacies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intimacies_player_id'))
        batch_op.drop_index(batch_op.f('ix_intimacies_boss_id'))

    op.drop_table('intimacies')
    with op.batch_alter_table('gift_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gift_orders_status'))
        batch_op.drop_index(batch_op.f('ix_gift_orders_staff_id'))
        batch_op.drop_index(batch_op.f('ix_gift_orders_player_id'))
        batch_op.drop_index(batch_op.f('ix_gift_orders_gift_id'))
        batch_op.drop_index(batch_op.f('ix_gift_orders_boss_id'))

    op.drop_table('gift_orders')
    op.drop_table('vip_levels')
    op.drop_table('gifts')
    with op.batch_alter_table('broadcast_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broadcast_configs_broadcast_type'))

    op.drop_table('broadcast_configs')
    # ### end Alembic commands ###
