"""add lottery tables

Revision ID: eb5dd5c67a9d
Revises: 4d37a208ec86
Create Date: 2026-03-02 10:37:20.947550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5dd5c67a9d'
down_revision = '4d37a208ec86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prize', sa.String(length=500), nullable=False),
    sa.Column('winner_count', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=100), nullable=False),
    sa.Column('kook_msg_id', sa.String(length=100), nullable=True),
    sa.Column('emoji', sa.String(length=50), nullable=True),
    sa.Column('eligible_roles', sa.Text(), nullable=True),
    sa.Column('min_vip_level', sa.String(length=50), nullable=True),
    sa.Column('draw_time', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('rigged_user_ids', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lotteries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lotteries_status'), ['status'], unique=False)

    op.create_table('lottery_winners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lottery_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kook_id', sa.String(length=50), nullable=False),
    sa.Column('is_rigged', sa.Boolean(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lottery_id'], ['lotteries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lottery_winners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lottery_winners_lottery_id'), ['lottery_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lottery_winners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lottery_winners_lottery_id'))

    op.drop_table('lottery_winners')
    with op.batch_alter_table('lotteries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lotteries_status'))

    op.drop_table('lotteries')
    # ### end Alembic commands ###
