"""Initial migration

Revision ID: fdc2d0bb174b
Revises: 
Create Date: 2026-02-28 00:15:21.386180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc2d0bb174b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('player_nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('badge', sa.String(length=50), nullable=True),
    sa.Column('user_code', sa.String(length=20), nullable=True),
    sa.Column('kook_id', sa.String(length=50), nullable=True),
    sa.Column('kook_username', sa.String(length=100), nullable=True),
    sa.Column('kook_bound', sa.Boolean(), nullable=True),
    sa.Column('wechat_openid', sa.String(length=100), nullable=True),
    sa.Column('wechat_bound', sa.Boolean(), nullable=True),
    sa.Column('m_coin', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('m_coin_gift', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('m_bean', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('m_bean_frozen', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('vip_level', sa.String(length=50), nullable=True),
    sa.Column('vip_discount', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('anonymous_recharge', sa.Boolean(), nullable=True),
    sa.Column('anonymous_gift_send', sa.Boolean(), nullable=True),
    sa.Column('anonymous_gift_recv', sa.Boolean(), nullable=True),
    sa.Column('anonymous_upgrade', sa.Boolean(), nullable=True),
    sa.Column('broadcast_channel', sa.String(length=100), nullable=True),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('register_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_code')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_kook_id'), ['kook_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_nickname'), ['nickname'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_player_nickname'), ['player_nickname'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_player_nickname'))
        batch_op.drop_index(batch_op.f('ix_users_nickname'))
        batch_op.drop_index(batch_op.f('ix_users_kook_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
